project:
  # name: "sharada_website"
  type: website
  output-dir: docs

output:
  html_document:
  theme: sandstone

website:
  navbar:
      background: dark
      left:
        - text: "Home"
          href: index.rmd
        - text: "About"
          href: about.rmd

